server:
  port: 8081

spring:
  application:
    name: dubbo-demo-provider

dubbo:
  application:
    name: dubbo-demo-provider
    id: dubbo-demo-provider
  protocol:
    id: dubbo
    name: dubbo
    port: 20880
  provider:
    retries: 0
    timeout: 600000
    validation: true
  consumer:
    retries: 0
  scan:
    base-packages: com.mao.dubbo.provider.service
  registry:
    address: zookeeper://42.192.154.95:2181