spring:
  application:
    name: spring-cloud-eureka-client
server:
  port: 8080

## Spring Cloud Eureka 服务器作为注册中心
## 通常情况下，不需要再注册到其他注册中心去 同时，它也不需要获取客户端信息
eureka:
  client:
    ### 向注册中心注册
    register-with-eureka: true
    ### 向注册中心获取注册信息（服务、实例信息）
    fetch-registry: true
    ### Spring Cloud Eureka 客户端 注册到 Eureka 服务器
    service-url:
      defaultZone: http://localhost:9090/eureka
