spring:
  application:
    name: spring-cloud-eureka-server
server:
  port: 9090

## Spring Cloud Eureka 服务器作为注册中心
## 通常情况下，不需要再注册到其他注册中心去 同时，它也不需要获取客户端信息
eureka:
  instance:
    hostname: localhost
    instance-id: eureka-server-1
  #    prefer-ip-address: false
  client:
    ### 向注册中心注册
    register-with-eureka: true
    ### 向注册中心获取注册信息（服务、实例信息）
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:9090/eureka
