server:
  #  port: 8090
  error:
    whitelabel:
      enabled: true
  servlet:
    encoding:
      force: true
spring:
  application:
    name: security
#  security:
#    user:
#      name: user
#      password: 123456
  datasource:
    initialization-mode: embedded
  messages:
    always-use-message-format: false
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: true
    use-code-as-default-message: false
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  profiles:
    active: "dev"
